# Generated by Django 5.2.4 on 2025-08-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_username'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('store', 'tax_name', 'tax_percentage')},
        ),
    ]
