# Generated by Django 5.2.4 on 2025-08-28 11:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_remove_customuser_username'),
        ('inventory', '0002_alter_tax_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_number', models.IntegerField()),
                ('Number_of_Seats', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tables',
                'ordering': ['Table_number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=0)),
                ('order_method', models.CharField(choices=[('Dine In', 'Dine In'), ('Takeaway', 'Takeaway'), ('Delivery', 'Delivery')], max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Kitchen', 'In Kitchen'), ('In Progress', 'In Progress'), ('Order Ready', 'Order Ready'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('checkout_status', models.BooleanField(default=False)),
                ('take_order', models.BooleanField(default=False)),
                ('completion_status', models.BooleanField(default=False)),
                ('is_saved_for_later', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Tabby', 'Tabby'), ('Bank Transfer', 'Bank Transfer'), ('Digital Wallet', 'Digital Wallet'), ('Split Payment', 'Split Payment'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Pending', max_length=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authentication.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.tables')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Tabby', 'Tabby'), ('Bank Transfer', 'Bank Transfer'), ('Digital Wallet', 'Digital Wallet'), ('Split Payment', 'Split Payment')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partial', 'Partial')], max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('service_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='orders.order')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_instructions', models.CharField(blank=True, max_length=500, null=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('is_saved_for_later', models.BooleanField(default=False)),
                ('added_to_order_date', models.DateTimeField(auto_now_add=True)),
                ('moved_to_checkout_date', models.DateTimeField(blank=True, null=True)),
                ('add_ons', models.ManyToManyField(blank=True, related_name='order_items', to='inventory.modifiers')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('tax', models.ManyToManyField(blank=True, related_name='order_items', to='inventory.tax')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SavedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('items_count', models.IntegerField(default=0)),
                ('total_saved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items_log', to='orders.order')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_date'],
            },
        ),
    ]
